jira:
  url: 'https://jyelee.atlassian.net'
  user: 'admin'
  passwd: 'Foobar123'
  project_key: 'TEST'
  issue_name: 'Bug'
  severity_criteria:
    Highest: 9,
    High: 7,
    Medium: 4,
    Low: 1
  resolution_workflow:
    fields:
      resolution:
        name: Done
